### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Using Google's zopflipng to recompress the png images losslessly.

```
 dev/theme-kit/bg-input-focus.png                  | Bin 143 -> 73 bytes
 dev/theme-kit/bg-input.png                        | Bin 143 -> 73 bytes
 dev/theme-kit/identification.png                  | Bin 19461 -> 14752 bytes
 dist/images/agent/bg-input-agent.png              | Bin 181 -> 89 bytes
 dist/images/agent/bg-input-focus-agent.png        | Bin 186 -> 93 bytes
 dist/images/agent/sprite-agent.png                | Bin 16545 -> 8809 bytes
 dist/images/aristo/bg-input-aristo.png            | Bin 192 -> 113 bytes
 dist/images/aristo/bg-input-focus-aristo.png      | Bin 186 -> 106 bytes
 dist/images/aristo/sprite-aristo.png              | Bin 20542 -> 18749 bytes
 dist/images/default/bg-input-focus.png            | Bin 143 -> 73 bytes
 dist/images/default/bg-input.png                  | Bin 143 -> 73 bytes
 dist/images/default/sprite.png                    | Bin 34770 -> 18810 bytes
 dist/images/jeans/bg-input-focus-jeans.png        | Bin 5690 -> 4011 bytes
 dist/images/jeans/bg-input-focus-retina-jeans.png | Bin 20340 -> 8516 bytes
 dist/images/jeans/bg-input-jeans.png              | Bin 5451 -> 3881 bytes
 dist/images/jeans/bg-input-retina-jeans.png       | Bin 19484 -> 8495 bytes
 dist/images/jeans/sprite-jeans.png                | Bin 599848 -> 469896 bytes
 dist/images/jeans/sprite-retina-jeans.png         | Bin 2071761 -> 1427129 bytes

```

### CODE REVIEW

**Comment by shehi** [comment]
I had to revert this PR as it damaged PNG files by converting them from 32bit to 16bit color palette and changing them considerably in color-basis.

**Comment by PeterDaveHello** [comment]
Do all the images have the same problem? I'll be happy to look into the issue.

**Comment by shehi** [comment]
@PeterDaveHello , yes, I am afraid so, as I noticed color brightness/shade change as well as bitmap-depth (32 to 16).  Please check at your end as well and let me know. Please pay special attention to sprites as they contain almost everything.

**Comment by PeterDaveHello** [comment]
@shehi would you please let me know the procedure you are using to verify the color brightness/shade change? Thanks.

**Comment by shehi** [comment]
Good old Photoshop.

**Comment by PeterDaveHello** [comment]
@shehi would you mind to share something like screenshot about the diff? Thanks.

**Comment by shehi** [comment]
image

**Comment by PeterDaveHello** [comment]
@shehi I use this command but found no difference:

```
compare -metric RMSE -verbose a.png b.png NULL:
```

The only difference may come from this zopflipng parameter, but it's not a visual difference:

`--lossy_transparent: remove colors behind alpha channel 0. No visual difference, removes hidden information.`

There are some others command can help valid the pixels, would you like to try? You know that sometimes visual make fake our eyes. BTW, actually, I use 500% size on the browser to help me found the difference, I found nothing here.

**Pull request merged**
