### PR TITLE
Add condition to check if checkbox is readonly

### PR DESCRIPTION
**Pull request by SpiderNeo1**
Add condition to check if the checkbox can be modified !

### CODE REVIEW

**Comment by shehi** [comment]
Please amend and re-commit the same thing to make Github recheck this PR again. Apparently we had Travis CI for this repo, which shouldn't have existed in first place.

**Comment by SpiderNeo1** [comment]
Hello,
How am I doing this?

**Comment by shehi** [comment]
git commit --amend
git push

**Comment by SpiderNeo1** [comment]
I don't use git...

**Comment by shehi** [comment]
Yet you are on Github! :) What an irony!

**Pull request closed without merging**
